### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by CodegoErgoSum** [BinaryKits/BinaryKits.Zpl#129]
The following code resulted in the subsequent error message at line 22 (See **`commented code line`** text).  The code is based on the **Example Code** shown on the [BinaryKits.Zpl.Viewer](https://github.com/BinaryKits/BinaryKits.Zpl/tree/master/src/BinaryKits.Zpl.Viewer) source page.

_Note: The _zpl_ is indeed valid **ZPL**._

```
using System.Collections.Generic;
using System.Drawing;
using System.IO;

using BinaryKits.Zpl.Viewer;

namespace ZplToImage
{
    public class ZplConverter
    {
        public Image[] ConvertToImages(string zpl)
        {
            IPrinterStorage printerStorage = new PrinterStorage();

            var drawer = new ZplElementDrawer(printerStorage);
            var analyzer = new ZplAnalyzer(printerStorage);
            var analyzeInfo = analyzer.Analyze(zpl);
            var images = new List<Image>();

            foreach (var labelInfo in analyzeInfo.LabelInfos)
            {
```
```C#
                var imageBytes = drawer.Draw(labelInfo.ZplElements); // This is where the exception is thrown.
```
```
                var image = ByteArrayToImage(imageBytes);

                images.Add(image);
            }

            return images.ToArray();
        }

        public Image ByteArrayToImage(byte[] byteArrayIn)
        {
            MemoryStream ms = new MemoryStream(byteArrayIn);
            Image returnImage = Image.FromStream(ms);

            return returnImage;
        }
    }
}
```

> status: ERROR
> error.code: -2
> error.description: Unexpected Error
> error.message: Index was outside the bounds of the array.
> error.message: System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at BinaryKits.Zpl.Viewer.ZplElementDrawer.Draw(ZplElementBase[] elements, Double labelWidth, Double labelHeight, Int32 printDensityDpmm)
>    at ZplToImage.ZplConverter.ConvertToImages(String zpl) in C:\Users\CodegoErgoSum\source\repos\CESServices\ZplToImage\ZplConverter.cs:line 22

**Comment by CodegoErgoSum** [comment]
The error occurs specifically when the _ZplElement_ is a `ZplDataMatrix` at line 41 (See **`commented code line`** text).  Class `DataMatrixElementDrawer` and errant method `Draw(ZplElementBase element)` are listed below.

A copy of the offending ZPL is attached to be able to exactly reproduce the error.

```
using BarcodeLib;
using BinaryKits.Zpl.Label.Elements;
using SkiaSharp;
using System.Drawing;
using ZXing;
using ZXing.Datamatrix;

namespace BinaryKits.Zpl.Viewer.ElementDrawers
{
    public class DataMatrixElementDrawer : BarcodeDrawerBase
    {
        ///<inheritdoc/>
        public override bool CanDraw(ZplElementBase element)
        {
            return element is ZplDataMatrix;
        }

        ///<inheritdoc/>
        public override void Draw(ZplElementBase element)
        {
            if (element is ZplDataMatrix dataMatrix)
            {
                float x = dataMatrix.PositionX;
                float y = dataMatrix.PositionY;

                if (dataMatrix.FieldTypeset != null)
                {
                    y -= dataMatrix.Height;
                }

                var writer = new DataMatrixWriter();
                var result = writer.encode(dataMatrix.Content, BarcodeFormat.DATA_MATRIX, 0, 0);

                int size = dataMatrix.Height;
                using var image = new SKBitmap(result.Width + size - 1, result.Height + size - 1);

                for (int row = 0; row < result.Height; row++)
                {
                    for (int col = 0; col < result.Width; col++)
                    {
```
```C#
                        var color = result[row, col] ? SKColors.Black : SKColors.White; // This is where the exception is thrown.
```
```
                        image.SetPixel(row, col, color);
                    }
                }

                using var resizedImage = image.Resize(new SKSizeI(image.Width * size, image.Height * size), SKFilterQuality.None);

                var png = resizedImage.Encode(SKEncodedImageFormat.Png, 100).ToArray();
                this.DrawBarcode(png, dataMatrix.Height, dataMatrix.Height, dataMatrix.FieldOrigin != null, x, y, dataMatrix.FieldOrientation);
            }
        }
    }
}
[label.txt](https://github.com/BinaryKits/BinaryKits.Zpl/files/9332455/label.txt)

```

**Comment by CodegoErgoSum** [comment]
The error occurs specifically when the _ZplElement_ is a `ZplDataMatrix` at line 41 (See **`commented code line`** text).  Class `DataMatrixElementDrawer` and errant method `Draw(ZplElementBase element)` are listed below.

A copy of the offending ZPL ([zpl.txt](https://github.com/BinaryKits/BinaryKits.Zpl/files/9332468/zpl.txt)) is attached to be able to exactly reproduce the error.

```
using BarcodeLib;
using BinaryKits.Zpl.Label.Elements;
using SkiaSharp;
using System.Drawing;
using ZXing;
using ZXing.Datamatrix;

namespace BinaryKits.Zpl.Viewer.ElementDrawers
{
    public class DataMatrixElementDrawer : BarcodeDrawerBase
    {
        ///<inheritdoc/>
        public override bool CanDraw(ZplElementBase element)
        {
            return element is ZplDataMatrix;
        }

        ///<inheritdoc/>
        public override void Draw(ZplElementBase element)
        {
            if (element is ZplDataMatrix dataMatrix)
            {
                float x = dataMatrix.PositionX;
                float y = dataMatrix.PositionY;

                if (dataMatrix.FieldTypeset != null)
                {
                    y -= dataMatrix.Height;
                }

                var writer = new DataMatrixWriter();
                var result = writer.encode(dataMatrix.Content, BarcodeFormat.DATA_MATRIX, 0, 0);

                int size = dataMatrix.Height;
                using var image = new SKBitmap(result.Width + size - 1, result.Height + size - 1);

                for (int row = 0; row < result.Height; row++)
                {
                    for (int col = 0; col < result.Width; col++)
                    {
```
```C#
                        var color = result[row, col] ? SKColors.Black : SKColors.White; // This is where the exception is thrown.
```
```
                        image.SetPixel(row, col, color);
                    }
                }

                using var resizedImage = image.Resize(new SKSizeI(image.Width * size, image.Height * size), SKFilterQuality.None);

                var png = resizedImage.Encode(SKEncodedImageFormat.Png, 100).ToArray();
                this.DrawBarcode(png, dataMatrix.Height, dataMatrix.Height, dataMatrix.FieldOrigin != null, x, y, dataMatrix.FieldOrientation);
            }
        }
    }
}
```

**Comment by CodegoErgoSum** [comment]
The error occurs specifically when the _ZplElement_ is a `ZplDataMatrix` at line 41 (See **`commented code line`** text).  Class `DataMatrixElementDrawer` and errant method `Draw(ZplElementBase element)` are listed below.

A copy of the offending ZPL ([zpl.txt](https://github.com/BinaryKits/BinaryKits.Zpl/files/9332473/zpl.txt)) is attached to be able to exactly reproduce the error.

```
using BarcodeLib;
using BinaryKits.Zpl.Label.Elements;
using SkiaSharp;
using System.Drawing;
using ZXing;
using ZXing.Datamatrix;

namespace BinaryKits.Zpl.Viewer.ElementDrawers
{
    public class DataMatrixElementDrawer : BarcodeDrawerBase
    {
        ///<inheritdoc/>
        public override bool CanDraw(ZplElementBase element)
        {
            return element is ZplDataMatrix;
        }

        ///<inheritdoc/>
        public override void Draw(ZplElementBase element)
        {
            if (element is ZplDataMatrix dataMatrix)
            {
                float x = dataMatrix.PositionX;
                float y = dataMatrix.PositionY;

                if (dataMatrix.FieldTypeset != null)
                {
                    y -= dataMatrix.Height;
                }

                var writer = new DataMatrixWriter();
                var result = writer.encode(dataMatrix.Content, BarcodeFormat.DATA_MATRIX, 0, 0);

                int size = dataMatrix.Height;
                using var image = new SKBitmap(result.Width + size - 1, result.Height + size - 1);

                for (int row = 0; row < result.Height; row++)
                {
                    for (int col = 0; col < result.Width; col++)
                    {
```
```C#
                        var color = result[row, col] ? SKColors.Black : SKColors.White; // This is where the exception is thrown.
```
```
                        image.SetPixel(row, col, color);
                    }
                }

                using var resizedImage = image.Resize(new SKSizeI(image.Width * size, image.Height * size), SKFilterQuality.None);

                var png = resizedImage.Encode(SKEncodedImageFormat.Png, 100).ToArray();
                this.DrawBarcode(png, dataMatrix.Height, dataMatrix.Height, dataMatrix.FieldOrigin != null, x, y, dataMatrix.FieldOrientation);
            }
        }
    }
}
```

**Comment by primo-ppcg** [comment]
The row and col appear to be swapped on lines 41 and 42 of DataMatrixElementDrawer:

```csharp
                        var color = result[row, col] ? SKColors.Black : SKColors.White;
                        image.SetPixel(row, col, color);
```

should read:

```csharp
                        var color = result[col, row] ? SKColors.Black : SKColors.White;
                        image.SetPixel(col, row, color);
```

That doesn't actually solve the problem though, it just exposes it. The ZXing library is returning a rectangular matrix.

```zpl2
^XA
^FO580,470^BXN,11,200,,,,_^FD00393580940000608087^FS
^XZ
```

<img src="https://user-images.githubusercontent.com/4907320/184529002-ba96a1da-ce6e-4097-84d2-806c3ed09d88.png" width="406" />

@tinohager Do you think this is a bug in ZXing, or a missing parameter?
